# -----------------------------------------------------------------------------
# File: starship.toml
# Author: Naveen Duhan
# Description: Starship prompt configuration with rounded segments.
# -----------------------------------------------------------------------------

format = """
[](fg:#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[os]
disabled = false
style = "bg:#9A348E fg:#ffffff"
format = "[$symbol ]($style)"

[os.symbols]
Arch = ""
Ubuntu = ""
Fedora = ""
Debian = ""
Linux = ""
Macos = ""
Windows = ""

[username]
show_always = true
style_user = "bg:#9A348E fg:#ffffff"
style_root = "bg:#9A348E fg:#ffffff"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#DA627D fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#ffffff"
format = '[ $symbol$context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#1e1e2e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#1e1e2e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[python]
symbol = " "
style = "bg:#86BBD8 fg:#1e1e2e"
format = '[ $symbol($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A fg:#ffffff"
format = '[ ♥ $time ]($style)'
